/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package virtualMachine

import virtualMachine.io.VMParser
import java.io.File
import java.nio.charset.Charset

class App {
    fun processInputFile(pathToInput: String) : VMParser {
        val file = File(pathToInput)
        val bufferedReader = file.bufferedReader(Charset.defaultCharset())
        val vmParser = VMParser()
        bufferedReader
                .lines()
                .forEach {
                    it -> vmParser.readLine(it)
                }
        //do nothing with processed stack for now
        return vmParser
    }
}

fun main(args: Array<String>) {
    App().processInputFile("/home/ed/Documents/Studying/mynand2tetris2/projects/07/StackArithmetic/StackTest/StackTest.vm")
}
